name: CoinHub API Server

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-coinhub}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-luckycube}
      PGDATA: /data/postgres
      POSTGRES_DB: ${DB_DATABASE:-coinhub}
    ports:
      - '5432:5432'
    volumes:
      - db:/data/postgres

  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    develop:
      watch:
        - path: src/
          target: /app/src/
          action: sync
        - path: package.json
          action: rebuild
    volumes:
      - ./.env:/app/.env
    # TODO: No husky please?

volumes:
  db:
