name: coinhub-api-server

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-coinhub}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-luckycube}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${DB_DATABASE:-coinhub}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
