providers = ['node']

[variables]
NIXPACKS_NODE_VERSION = '23.9.0'

[phases.install]
cmds = ['npm ci --omit=dev --no-scripts']
# cacheDirectories = [
#   'node_modules', # default is node_modules/.cache but railway fukup on us
# ]

[phases.build]
cmds = ['npm run build']

[start]
runImage = 'node:23.9.0-alpine'
cmd = 'npm run start'
