# providers = ['node']

[variables]
# NIXPACKS_NODE_VERSION = '23.9'
CI = 'false'
NODE_ENV = 'production'
TZ = 'TZ=Asia/Ho_Chi_Minh'

[phases.setup]
nixPkgs = ['nodejs_23']

[phases.install]
cmds = ['npm install --omit=dev --ignore-scripts']
cacheDirectories = ['~/.npm', '/app/node_modules']

[phases.build]
cmds = ['npx nest build']

[start]
runImage = 'node:23.9.0-alpine'
cmd = 'node /app/dist/src/main'
