providers = ['node']

[phases.setup]
nixPkgs = ['nest-cli']

[phases.install]
cmds = ['npm ci --omit=dev --no-scripts']
cacheDirectories = [
  '.cache',
] # default is node_modules/.cache but railway fukup on us

[phases.build]
cmds = ['npm run build']

[start]
runImage = 'node:23.9.0-alpine'
cmd = 'npm run start'
