services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-luckycube}
      POSTGRES_DB: ${DB_DATABASE:-coinhub}
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
