name: Code check

on:
  push:
    branches:
      - '**'
    paths:
      - 'src/**'
      - 'lib/**'
      - 'test/**'
      - 'scripts/**'
      - 'database/**'
  pull_request:
    paths:
      - 'src/**'
      - 'lib/**'
      - 'test/**'
      - 'scripts/**'
      - 'database/**'

jobs:
  check:
    runs-on: ubuntu-latest
    name: check
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Type checking
        run: npx tsc --noEmit

      - name: ESlint Checking
        run: npx eslint 'src/*'

      - name: Prettier Checking
        run: npx prettier 'src/*' --check
