name: Supabase deploy

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_PAT }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Get FCM service account
        run: curl '${{ secrets.FCM_SERVICE_ACCOUNT }}' -o 'supabase/functions/service-account.json'

      - name: Deploy function
        run: supabase functions deploy --project-ref "$PROJECT_ID"
